# Generated by Django 5.2.7 on 2025-10-07 09:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('telegram', models.CharField(blank=True, max_length=128, verbose_name='Телеграм')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('date_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', upload_to='avatar/', verbose_name='Аватар')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Необходимо ввести номер телефона в формате: +70123456789, допускается до 15 знаков', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Пол')),
                ('role', models.CharField(choices=[('s', 'Student'), ('t', 'Teacher')], max_length=1, verbose_name='Роль')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Баланс')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
