# Generated by Django 5.2.7 on 2025-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher')], default='s', max_length=1, verbose_name='Роль'),
        ),
    ]
