"""lesson video|practica

Revision ID: 00e3c0e61e56
Revises: e590ab6a2572
Create Date: 2026-03-25 16:02:54.876224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e3c0e61e56'
down_revision: Union[str, Sequence[str], None] = 'e590ab6a2572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_lessons')
    op.drop_table('practicas')
    # ### end Alembic commands ###
