"""test visibility

Revision ID: 817c8374b2fb
Revises: c257bfe86196
Create Date: 2026-04-02 10:43:27.372208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817c8374b2fb'
down_revision: Union[str, Sequence[str], None] = 'c257bfe86196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_lessons', sa.Column('is_visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_lessons', 'is_visibility')
    # ### end Alembic commands ###
