"""Update table User

Revision ID: 909c11ed5780
Revises: 18bc58e0387f
Create Date: 2025-11-19 14:06:32.369060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '909c11ed5780'
down_revision: Union[str, Sequence[str], None] = '18bc58e0387f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('users', sa.Column('gender', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'balance')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
