"""Update table password

Revision ID: e68f5a449b6c
Revises: acefadf8d4f2
Create Date: 2025-11-24 15:06:20.696871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68f5a449b6c'
down_revision: Union[str, Sequence[str], None] = 'acefadf8d4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_passowrd', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_passowrd')
    # ### end Alembic commands ###
